//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carts_jnl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carts_jnl()
        {
            this.Cart_products_jnl = new HashSet<Cart_products_jnl>();
        }
    
        public int Cart_id { get; set; }
        public string Invoice_number { get; set; }
        public double Total_price { get; set; }
        public System.DateTime Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_products_jnl> Cart_products_jnl { get; set; }
    }
}
